#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --libexecdir=/usr/lib \
    --disable-pam-session \
    --disable-root-mailer \
    --disable-nls \
    --enable-pie \
    --without-pam \
    --without-sendmail \
    --with-ignore-dot \
    --with-insults=disabled \
    --with-logfac=auth \
    --with-passprompt="[sudo] password for %p: "

make
make \
    DESTDIR="$1" \
    install_uid="$(id -u)" \
    install_gid="$(id -g)" \
    install
