#!/bin/sh -e

patch -p1 < fontconfig-fix-1744377.patch

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts

make
make DESTDIR="$1" install
