#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts

make
make DESTDIR="$1" install

# Remove docs and other unneeded files.
rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/gettext"
rm -rf "$1/usr/share/locale"
rm -rf "$1/usr/share/man/man3"
