#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-included-gettext \
    --without-examples \
    --disable-java \
    --disable-native-java \
    --disable-csharp \
    --disable-libasprintf \
    --disable-acl \
    --without-git \
    --disable-openmp \
    --disable-curses

make
make DESTDIR="$1" install

# Fix conflict with musl.
[ -e "$1/usr/include/libintl.h" ] && {
    mkdir -p "$1/usr/include/gettext"
    mv "$1/usr/include/libintl.h" "$1/usr/include/gettext"
}
