#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-included-gettext \
    --without-examples \
    --disable-java \
    --disable-native-java \
    --disable-csharp \
    --disable-libasprintf \
    --disable-acl \
    --without-git \
    --disable-openmp \
    --disable-curses

make
make DESTDIR="$1" install
