#!/bin/sh -e

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --enable-targets=x86_64-pep \
    --disable-multilib \
    --disable-werror \
    --disable-nls \
    --with-mmap \
    --with-system-zlib

make
make DESTDIR="$1" install
