#!/bin/sh -e

./configure \
    --prefix=/usr \
    --datadir=/usr/share/openssh \
    --sysconfdir=/etc/ssh \
    --without-selinux \
    --with-privsep-user=nobody \
    --with-mantype=doc \
    --without-rpath \
    --disable-strip \
    --with-ssl-engine \
    --with-pid-dir=/run \
    --disable-wtmp \
    --disable-utmp

make
make DESTDIR="$1" install

install -m 755 contrib/ssh-copy-id "$1/usr/bin/ssh-copy-id"
install -m 644 contrib/ssh-copy-id.1 "$1/usr/share/man/man8/ssh-copy-id.1"

# Install runit services.
install -Dm 755 sshd.run "$1/etc/sv/sshd/run"
ln -s /run/runit/supervise.sshd "$1/etc/sv/sshd/supervise"
