#!/bin/sh -e

# During ./configure, disable kill and sulogin as they are provided
# by busybox.
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --bindir=/usr/bin \
    --sbindir=/usr/bin \
    --libdir=/usr/lib \
    --enable-libuuid \
    --enable-libblkid \
    --enable-fsck \
    --disable-makeinstall-chown \
    --disable-rpath \
    --disable-kill \
    --disable-sulogin \
    --without-udev \
    --without-python \
    --without-systemd

make
make DESTDIR="$1" install
