#!/bin/sh -e

export DESTDIR="$1"

sed "/subdir('tests')/d" meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dgir=false \
    -Djasper=false \
    -Djpeg=true \
    -Dpng=true \
    -Dtiff=true \
    -Ddocs=false \
    -Dman=false \
    -Dgio_sniffing=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output
ninja -C output install
