#!/bin/sh -e

export CFLAGS="$CFLAGS -D_PR_POLL_AVAILABLE -D_PR_HAVE_OFF64_T -D_PR_INET6 -D_PR_HAVE_INET_NTOP -D_PR_HAVE_GETHOSTBYNAME2 -D_PR_HAVE_GETADDRINFO -D_PR_INET6_PROBE"

cd nspr

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --includedir=/usr/include/nspr \
    --enable-optimize \
    --enable-ipv6 \
    --enable-64bit

make
make DESTDIR="$1" install

install -Dm755 config/nspr-config "$1/usr/bin/nspr-config"
install -Dm644 config/nspr.pc     "$1/usr/lib/pkgconfig/nspr.pc"
rm -rf "$1/usr/bin/prerr.properties" \
       "$1/usr/bin/compile-et.pl" \
       "$1/usr/share/aclocal/nspr.m4" \
       "$1/usr/include/nspr/md"
