#!/bin/sh -e

./configure \
    --prefix=/usr \
    --without-xmlwf \
    --without-examples \
    --without-tests \
    --without-docbook

make
make DESTDIR="$1" install

# Remove documentation (Changelogs, etc).
# False positive.
# shellcheck disable=SC2115
rm -rf "$1/usr/share"
