#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Remove gettext requirement.
sed -i 's/ngettext/printf/g' Tools/MiniBrowser/gtk/BrowserDownloadsBar.c
sed -i '/po_files *.po/d'    Source/WebCore/platform/gtk/po/CMakeLists.txt
sed -i '/^GETTEXT_C/d'       Source/WebCore/platform/gtk/po/CMakeLists.txt

export DESTDIR="$1"

cmake -B build \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_INSTALL_PREFIX=/usr \
	-DLIB_INSTALL_DIR=/usr/lib \
	-DPORT=GTK \
	-DCMAKE_SKIP_RPATH=ON \
	-DENABLE_BUBBLEWRAP_SANDBOX=OFF \
	-DENABLE_GEOLOCATION=OFF \
	-DENABLE_GLES2=ON \
	-DENABLE_INTL=OFF \
	-DENABLE_INTROSPECTION=OFF \
	-DENABLE_MINIBROWSER=OFF \
	-DENABLE_OPENGL=OFF \
	-DENABLE_SPELLCHECK=OFF \
	-DENABLE_VIDEO=OFF \
	-DENABLE_WEBGL=OFF \
	-DENABLE_WEB_AUDIO=OFF \
	-DUSE_LIBHYPHEN=OFF \
	-DUSE_LIBNOTIFY=OFF \
	-DUSE_LIBSECRET=OFF \
	-DUSE_OPENJPEG=OFF \
	-DUSE_WOFF2=OFF \
	-DUSE_WPE_RENDERER=OFF \
    -DENABLE_WEB_CRYPTO=OFF \
	-Wno-dev

cmake --build   build
cmake --install build
