#!/bin/sh -e

# Don't build with gettext.
sed -i "s|subdir('po')||g" meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddocs=false \
    -Dintrospection=false \
    . output

ninja -C output

DESTDIR="$1" ninja -C output install
