#!/bin/sh -e

sed -i '/chown/d' bsd.prog.mk

./configure \
    --enable-static \
    --with-shadow \
    --with-timestamp \
    --without-pam

make
make DESTDIR="$1" install

install -Dm600 doas.conf "$1/etc/doas.conf"
