#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin

make
make DESTDIR="$1" install

mkdir -p \
    "$1/etc/acpi/events" \
    "$1/etc/sv/acpid"

cp -f acpid.run "$1/etc/sv/acpid/run"
ln -sf /run/runit/supervise.acpid "$1/etc/sv/acpid/supervise"

