#!/bin/sh

cat <<EOF

NOTE: Install the 'hicolor-icon-theme' package if
      no other icon themes are installed.

NOTE: Install the 'firefox-privacy' package to
      enable extra privacy restrictions. This 
      includes more telemetry removals, hardened 
      settings, no phoning-home etc.

NOTE: You must set this environment variable.

      export MOZ_ENABLE_WAYLAND=1

NOTE: For VAAPI to work with amdgpu you must have 
      CHECKPOINT_RESTORE enabled in your kernel.
      See: https://lwn.net/Articles/845448/

      CONFIG_CHECKPOINT_RESTORE=y

EOF
