#!/bin/sh

cat <<EOF

NOTE: Install the 'hicolor-icon-theme' package if
      no other icon themes are installed.

NOTE: Install the 'firefox-privacy' package to
      enable extra privacy restrictions. This 
      includes more telemetry removals, hardened 
      settings, no phoning-home etc.

NOTE: You must set this environment variable.

      export MOZ_ENABLE_WAYLAND=1

NOTE: For VAAPI to work with amdgpu you must have 
      CHECKPOINT_RESTORE enabled in your kernel.
      See: https://lwn.net/Articles/845448/

      CONFIG_CHECKPOINT_RESTORE=y

NOTE: For VAAPI to work you must enable the following 
      in about:config

      gfx.webrender.all=true
      media.av1.enabled=false
      media.ffmpeg.dmabuf-textures.enabled=true
      media.ffmpeg.vaapi.enabled=true
      media.ffvpx.enabled=false

      You may also have to set the following
      environment variable.

      export MOZ_WAYLAND_DRM_DEVICE=/dev/dri/renderD128

EOF
