#!/bin/sh -e

mkdir -p build
cd build

cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_RTTI=ON \
    -DLLVM_ENABLE_EH=ON \
    -Wno-dev -G "Unix Makefiles" ..

make
make DESTDIR="$1" install
