#!/bin/sh -e

# setup base directories
for d in boot dev etc home mnt usr var opt run; do
    install -d -m755 "$1"/"$d"
done
install -d -m555 "$1"/proc
install -d -m555 "$1"/sys
install -d -m0750 "$1"/root
install -d -m1777 "$1"/tmp

# setup /usr hierarchy
for d in bin include lib lib32 share src; do
    install -d -m755 "$1"/usr/"$d"
done

# setup manpages directories
for d in 1 2 3 4 5 6 7 8; do
    install -d -m755 "$1"/usr/share/man/man"$d"
done

# add symlinks
ln -s usr/bin "$1"/bin
ln -s usr/bin "$1"/sbin
ln -s bin "$1"/usr/sbin
ln -s usr/lib "$1"/lib
ln -s usr/lib "$1"/lib64
ln -s lib "$1"/usr/lib64

# setup /var
for d in cache local opt log/old lib/misc empty; do
    install -d -m755 "$1"/var/"$d"
done
install -d -m1777 "$1"/var/tmp
install -d -m1777 "$1"/var/spool/mail
ln -s spool/mail "$1"/var/mail
ln -s ../run "$1"/var/run
ln -s ../run/lock "$1"/var/lock

# setup /usr/local (usually for any programs installed outside package manager)
for d in bin etc games include lib man sbin share src; do
    install -d -m755 "$1"/usr/local/"$d"
done
ln -s ../man "$1"/usr/local/share/man

# /etc skeleton files
for f in crypttab fstab host.conf hosts issue os-release passwd profile securetty shadow shells; do
    install -m644 "$f" "$1"/etc
done
ln -s /proc/self/mounts "$1"/etc/mtab
