#!/bin/sh -e

machine=$(cc -dumpmachine)

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --build="$machine" \
    --host="$machine" \
    --disable-blkid

make
make DESTDIR="$1" install
