#!/bin/sh -e

rm -rf Modules/zlib
rm -rf Modules/expat
rm -rf Modules/_ctypes/darwin*
rm -rf Modules/_ctypes/libffi*

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

ln -s python3 "$1/usr/bin/python"
