#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

cp -f update-certdata.sh "$1/etc/ssl"

# Remove library documentation.
rm -rf "$1/usr/share/man/man3"
