#!/bin/sh -e

patch -p1 < evdev-wrap.patch

export CFLAGS="$CFLAGS -fPIC"

for pkg in mtdev evdev; do (
    cd "$pkg"

    ./configure \
        --prefix=/usr \
        --disable-shared \
        --disable-gcov

    make
    make DESTDIR="$OLDPWD" install
) done

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

export PKG_CONFIG_PATH="$PWD/usr/lib/pkgconfig"
export CFLAGS="$CFLAGS -I$PWD/usr/include -L$PWD/usr/lib"
export CFLAGS="$CFLAGS -I$PWD/usr/include/libevdev-1.0"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddefault_library=both \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . output

ninja -C output
ninja -C output install
