#!/bin/sh -e

patch -p1 < evdev-wrap.patch

export CFLAGS="$CFLAGS -fPIC"

# Clang reports error because of -Werror, using the CFLAGS below since
# in some cases, it's unused. Force -Wno-error in this case.
sed 's/Werror-Wno-error/' meson.build > _
mv -f _ meson.build

for pkg in mtdev evdev; do (
    cd "$pkg"

    ./configure \
        --prefix=/usr \
        --disable-shared \
        --disable-gcov

    make
    make DESTDIR="$OLDPWD" install
) done

export PKG_CONFIG_PATH="$PWD/usr/lib/pkgconfig"
export CFLAGS="$CFLAGS -I$PWD/usr/include -L$PWD/usr/lib"
export CFLAGS="$CFLAGS -I$PWD/usr/include/libevdev-1.0"
export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddefault_library=both \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . output

ninja -C output
ninja -C output install
