#!/bin/sh -e

export CFLAGS="$CFLAGS -UGDK_PIXBUF_DISABLE_DEPRECATED"
./configure \
    --build="$(cc -dumpmachine)" \
    --host="$(cc -dumpmachine)" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-nls \
    --enable-debug=no \
    --disable-gtk-doc \
    --with-xinput=yes

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
# TODO: Make GTK+2 build with demos.
sed -i -e 's/demos //g' Makefile

make
make DESTDIR="$1" install

# Remove a boat load of HTML documentation.
rm -rf "$1/gtk-doc/"
rm "$1/usr/bin/gtk-update-icon-cache"
