#!/bin/sh -e

cp -v configfsf.guess config.guess
cp -v configfsf.sub   config.sub

./configure \
    --prefix=/usr \
    --localstatedir=/var/state/gmp \
    --build="$(gcc -dumpmachine)" \
    --enable-cxx \
    --enable-fat \
    --with-pic

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"
