#!/bin/sh -e

./configure \
    --prefix=/usr \
    --localstatedir=/var/state/gmp \
    --enable-cxx \
    --with-pic

make
make DESTDIR="$1" install

# Remove all info files.
rm -rf "$1/usr/share/info"
