#!/bin/sh -e

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/doc/kiss"

cp -f kiss contrib/* "$1/usr/bin/"

for doc in docs/site/*.txt doc/*.txt; do case ${doc%%.txt} in
    README|news|blog|screenshots)
        # Skip.
    ;;

    *)
        cp -f "$doc" "$1/usr/share/doc/kiss/${doc##*/}"
    ;;
esac done

cp -r wiki "$1/usr/share/doc/kiss/wiki"
