#!/bin/sh

cat <<EOF

NOTE: Updates will now show a warning from Git about
      the merge strategy. Simply set the desired merge strategy
      and the warning will disappear.

Examples:

git config pull.rebase false  # merge (the default strategy)
git config pull.rebase true   # rebase
git config pull.ff only       # fast-forward only

TIP: --global can be used to set this user-wide.

EOF
