#!/bin/sh -e

patch -p0 < musl-ipv6.patch
sed -i '/<linux\/if_bridge.h>/i#define _LINUX_IN6_H' lib/route/link/bridge.c

./configure \
    --prefix=/usr \
    --disable-static

make
make DESTDIR="$1" install
