#!/bin/sh -e

sed 's|/lib|/usr/lib|g' Makefile > _
mv -f _ Makefile

# pkgconf is only used to check for obstack support
# which we don't have. The build works fine without
# this line, this just hides the errors.
#
# Also see: https://github.com/pullmoll/musl-obstack/
make PKG_CONFIG=/bin/true
make install
