#!/bin/sh -e

sed 's|/lib|/usr/lib|g' Makefile > _
mv -f _ Makefile

# pkgconf is only used to check for obstack support
# which we don't have. The build works fine without
# this line, this just hides the errors.
#
# Also see: https://github.com/pullmoll/musl-obstack/
export PKG_CONFIG=/bin/true

make LINKER_PATH=/usr/lib/ld-musl-x86_64.so.1
make DESTDIR="$1" install

ln -s ld-linux.so.2 "$1/usr/lib/ld-linux-x86-64.so.2"

