#!/bin/sh -e

# Don't build with tests or gettext.
sed -i "s|subdir('tests')||g" -i meson.build
sed -i "s|subdir('po')||g"    -i meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dgir=false \
    -Djasper=false \
    -Dpng=true \
    -Ddocs=false \
    -Dman=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output

DESTDIR="$1" ninja -C output install
