#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Dgir=false \
    -Djasper=false \
    -Dpng=true \
    -Ddocs=false \
    -Dman=false \
    -Dinstalled_tests=false \
    -Dbuiltin_loaders=all \
    . output

ninja -C output
ninja -C output install
