#!/bin/sh -e

# As KISS doesn't support repository packages as
# binaries per se, this build file simply spawns
# a second instance of 'kiss' to install the tarball.
#
# This could have just unpacked the tarball and
# repacked it (as is done with shellcheck-bin and
# pandoc-bin) but due to its size, this workaround
# is needed.
printf 'Installing firefox-bin\n'

# The tarball is hosted on GitHub which doesn't allow
# for the file naming scheme the package manager uses
# for its built tarballs (pkg#ver-rel.tar.gz).
mv -f "firefox-bin.68.4.1esr-1.tar.gz?no-extract" \
      "firefox#68.4.1esr-1.tar.gz"

# Install the package as you would any other you have
# built yourself. In reality, I could have just given
# a link to this tarball and asked you to run this
# command yourself.
#
# I'm nice though and want this to fit into the system
# like any other package.
KISS_FORCE=1 kiss i "$PWD/firefox#68.4.1esr-1.tar.gz"

cat <<EOF

NOTE: The 'Terminated' message below is fine and is a
      side-effect of how this package works and is
      temporary.

For more information, see the 'build' file.

EOF

kill 0
