#!/bin/sh -e

export LDFLAGS="-Wl,-z,lazy"
export DESTDIR="$1"

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    . build

ninja -C build
ninja -C build install
