#!/bin/sh -e

export LDFLAGS="-Wl,-z,lazy"

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

autoreconf -i

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    --with-default-dri=3

make
make DESTDIR="$1" install
