#!/bin/sh -e

patch -p1 < portability.patch
patch -p1 < fix-stdio-usage.patch
patch -p1 < mlockall-default-config.patch
patch -p1 < musl-fix-include.patch
patch -p1 < disable-symver.patch
patch -p1 < 001-include_fix.patch

# POSIX sh 'fmt -1' script.
mkdir -p fakebin
cat > fakebin/fmt <<EOF
#!/bin/sh -f
printf '%s\n' \$(cat -)
EOF
chmod +x fakebin/fmt

export PATH=$PATH:$PWD/fakebin
export MKDIR_P="install -d"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-selinux \
    --disable-nls \
    --enable-pkgconfig \
    --enable-fsadm \
    --enable-dmeventd \
    --enable-cmdlib \
    --enable-udev_sync \
    --enable-udev_rules \
    --enable-symvers=no \
    --disable-symvers \
    --with-default-dm-run-dir=/run \
    --with-default-locking-dir=/run/lock/lvm \
    --with-default-pid-dir=/run \
    --with-default-run-dir=/run/lvm

make V=1 DESTDIR="$1" install

# Make all libraries and binaries writable.
chmod -v u+w "$1/usr/lib/"* \
             "$1/usr/include/"* \
             "$1/usr/bin/"*
