#!/bin/sh -e

chown root:input "$KISS_ROOT/usr/bin/sway"
chmod g+s        "$KISS_ROOT/usr/bin/sway"

cat <<EOF

NOTE: You must be in the 'video' group.

NOTE: You must set XDG_RUNTIME_DIR in your shellrc
      or .profile for things to work. This directory
      must exist and must be writable by your user.

      export XDG_RUNTIME_DIR=/run/user/\$(id -u)

EOF
