#!/bin/sh -e

chown root:input "$KISS_ROOT/usr/bin/sway"
chmod g+s        "$KISS_ROOT/usr/bin/sway"

cat <<EOF

NOTE: You must be in the 'video', 'audio', and 'tty' 
      groups. There is no 'input' group requirement 
      as this sway binary is setgid input.

NOTE: You must set XDG_RUNTIME_DIR in your shellrc
      or .profile for things to work. This directory
      must exist and must be writable by your user.

      export XDG_RUNTIME_DIR=/run/user/\$(id -u)

NOTE: You must be the first to call DRMSetMaster.

      If you cannot fulfil this requirement, you must
      use the 'sway' package and run the 'seatd' daemon.

      Another option is to setuid root the sway binary.

EOF
