#!/bin/sh -e

make \
    prefix=/usr \
    CC="${CC:-gcc} $CFLAGS $CXXFLAGS" \
    -f unix/Makefile generic

make \
    prefix="$1/usr" \
    MANDIR="$1/usr/share/man/man1" \
    -f unix/Makefile install

