#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --enable-symlink-install \
    --disable-uuidd \
    --disable-libuuid \
    --disable-libblkid \
    --disable-elf-shlibs \
    --disable-fsck

# MKDIR_P fixes an install issue on musl/busybox.
make
make MKDIR_P="install -d" DESTDIR="$1" install install-libs

# Make static libraries writable.
chmod -v u+w "$1/usr/lib/"*.a
