#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    --enable-symlink-install \
    --disable-elf-shlibs \
    --disable-fsck \
    --disable-nls

# MKDIR_P fixes an install issue on musl/busybox.
make
make MKDIR_P="install -d" DESTDIR="$1" install install-libs

# Make static libraries writable (for strip).
chmod -v u+w "$1/usr/lib/libcom_err.a" \
             "$1/usr/lib/libe2p.a" \
             "$1/usr/lib/libext2fs.a" \
             "$1/usr/lib/libss.a"

# Remove all info files.
rm -rf "$1/usr/share/info"
