#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-static

make
make DESTDIR="$1" install

# Remove library documentation.
# False positive.
# shellcheck disable=2115
rm -rf "$1/usr/share"
