#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-malloc0returnsnull

make
make DESTDIR="$1" install

# Remove XML documentation.
# False positive.
# shellcheck disable=2115
rm -rf "$1/usr/share"
