#!/bin/sh -e

machine=$(gcc -dumpmachine)

./configure \
    --prefix=/usr \
    --build="$machine" \
    --target="$machine" \
    --host="$machine" \
    --disable-selinux \
    --enable-static-cryptsetup \
    --enable-libargon2 \
    --disable-blkid

make
make DESTDIR="$1" install
