#!/bin/sh -e

export SETUPTOOLS_INSTALL_WINDOWS_SPECIFIC_FILES=0

python3 bootstrap.py
python3 setup.py build
python3 setup.py install \
    --prefix=/usr \
    --root="$1" \
    --optimize=1 \
    --skip-build
