#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=tllist \
    -Djpeg=enabled \
    -Dpng=enabled \
    . output

ninja -C output
ninja -C output install
