#!/bin/sh -e

(
    cd skalibs

    ./configure \
        --prefix=/usr \
        --enable-allstatic

    make
    make DESTDIR="$PWD/.." install
)

kiss l execline && _execline=enable

./configure \
    --prefix=/usr \
    --libexecdir=/usr/lib/s6 \
    --libdir=/usr/lib \
    --with-sysdeps="$PWD/usr/lib/skalibs/sysdeps" \
    --with-lib="$PWD/usr/lib/skalibs" \
    --with-include="$PWD/usr/include" \
    --enable-allstatic \
    "--${_execline:-disable}-execline"

make
make install

# Install manual pages.
(
    cd man

    export MANPATH=$1/usr/share/man

    make
    make install
)

# Install baseinit files for using s6-svscan as PID 1.
{
    set -f

    # shellcheck source=/dev/null
    . /etc/rc.conf || :

    # Intentional, globbing disabled.
    # shellcheck disable=2086
    "$CC" -static -std=c99 -o "$1/usr/bin/init" init.c \
        -DCONFIG_SERVICE_DIR="\"${CONFIG_SERVICE_DIR:-/var/service}\"" \
        $CFLAGS $CPPFLAGS $LDFLAGS

    cp -f poweroff "$1/usr/bin"
    ln -s poweroff "$1/usr/bin/reboot"
}

