#!/bin/sh -e

make
make install

# Work around no 'DESTDIR'.
cp -a _install/. "$1"

# install runit services
install -Dm755 acpid.run "$1/etc/sv/acpid/run"
install -Dm755 udhcpc.run "$1/etc/sv/udhcpc/run"
ln -s /run/runit/supervise.acpid "$1/etc/sv/acpid/supervise"
ln -s /run/runit/supervise.acpid "$1/etc/sv/udhcpc/supervise"
