#!/bin/sh -e

# A painful collection of patches, some written for KISS and
# the others ported and modified from much older versions of LVM.
patch -p1 < portability.patch
patch -p1 < fix-stdio-usage.patch
patch -p1 < mlockall-default-config.patch
patch -p1 < musl-fix-include.patch
patch -p1 < disable-symver.patch
patch -p1 < 001-include_fix.patch

# LVM2 calls 'fmt -1' throughout the build process.
# This is a part of the GNU coreutils and is not included
# in KISS. All 'fmt -1' does is split each word in a string
# on a new line so lets just use the shell as an alternative.
mkdir -p fakebin
cat > fakebin/fmt <<EOF
#!/bin/sh -f
printf '%s\n' \$(cat -)
EOF
chmod +x fakebin/fmt
export PATH=$PATH:$PWD/fakebin

# The build fails when using busybox's 'mkdir'(?),
# swap to using 'install -d' instead which works.
export MKDIR_P="install -d"

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-selinux \
    --enable-pkgconfig \
    --enable-fsadm \
    --enable-dmeventd \
    --enable-cmdlib \
    --enable-udev_sync \
    --enable-udev_rules \
    --enable-symvers=no \
    --disable-symvers \
    --with-default-dm-run-dir=/run \
    --with-default-locking-dir=/run/lock/lvm \
    --with-default-pid-dir=/run \
    --with-default-run-dir=/run/lvm

make DESTDIR="$1" install

# Make all libraries and binaries writable.
chmod -v u+w "$1/usr/lib/"* \
             "$1/usr/include/"* \
             "$1/usr/bin/"*
