#!/bin/sh -e

export CFLAGS="$CFLAGS -UGDK_PIXBUF_DISABLE_DEPRECATED"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-debug=no \
    --disable-gtk-doc \
    --with-xinput=yes

make
make DESTDIR="$1" install

rm -f  "$1/usr/bin/gtk-update-icon-cache"
rm -f  "$1/usr/bin/gtk-demo"
rm -rf "$1/usr/share/gtk-2.0/demo"
