#!/bin/sh -e

triplet=$(cc -dumpmachine)
export CFLAGS="$CFLAGS -UGDK_PIXBUF_DISABLE_DEPRECATED"

./configure \
    --build="$triplet" \
    --host="$triplet" \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-debug=no \
    --disable-gtk-doc \
    --with-xinput=yes

sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
sed -i -e 's/demos //g' Makefile

make
make DESTDIR="$1" install

# Remove a boat load of HTML documentation.
rm -rf "$1/gtk-doc/"
rm -f  "$1/usr/bin/gtk-update-icon-cache"
