#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

sed -i 's/dbus//g' \
    src/buildtools/config/support.pri

sed -i 's/use_dbus.*/use_dbus=false/' \
    src/3rdparty/chromium/build/config/features.gni

qmake -- \
    -feature-webengine-system-icu \
    -feature-webengine-system-ninja \
    -feature-webengine-system-zlib \
    -feature-webengine-system-harfbuzz \
    -feature-webengine-system-png \
    -feature-webengine-system-libevent \
    -feature-webengine-system-libvpx \
    -feature-webengine-system-opus \
    -feature-webengine-system-libwebp \
    -feature-webengine-system-ffmpeg \
    -no-feature-webengine-system-glib \
    -no-feature-webengine-webrtc \
    -no-feature-webengine-proprietary-codecs \

make
make install INSTALL_ROOT="$1"
