#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Remove dbus dependency.
{
    sed -i 's/dbus//g' \
        src/buildtools/config/support.pri

    sed -i 's/use_dbus.*/use_dbus=false/' \
        src/3rdparty/chromium/build/config/features.gni
}

# Fix nasm hardcoded glibcism
sed -i '/CANONICALIZE_FILE_NAME/d' \
    src/3rdparty/chromium/third_party/nasm/config/config-linux.h

# Remove glibc header.
sed -i '/execinfo.h/d' \
    src/3rdparty/chromium/base/debug/stack_trace_posix.cc

# Remove udev dependency.
sed -i '/use_udev/s/=.*/=false/' \
    src/3rdparty/chromium/build/config/features.gni

qmake QMAKE_CXXFLAGS=-DQT_NO_ACCESSIBILITY -- \
    -feature-webengine-system-ninja \
    -feature-webengine-system-zlib \
    -feature-webengine-system-harfbuzz \
    -feature-webengine-system-png \
    -feature-webengine-system-libevent \
    -feature-webengine-system-libvpx \
    -feature-webengine-system-opus \
    -feature-webengine-system-libwebp \
    -feature-webengine-system-ffmpeg \
    -no-feature-webengine-system-icu \
    -no-feature-webengine-system-glib \
    -no-feature-webengine-webrtc \
    -no-feature-webengine-proprietary-codecs

make
make install INSTALL_ROOT="$1"
