#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    -Dlibproxy=disabled \
    -Dopenssl=enabled \
    . output

ninja -C output
ninja -C output install
