#!/bin/sh -e

make CC="${CC:-cc}" EFIDIR=/boot/EFI efibootmgr

mkdir -p \
    "$1/usr/bin" \
    "$1/usr/share/man/man8"

cp -f src/efibootmgr   "$1/usr/bin"
cp -f src/efibootmgr.8 "$1/usr/share/man/man8"
