#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-cxx \
    --disable-zstd \
    --disable-webp \
    --without-x

make
make DESTDIR="$1" install

# Remove HTML documentation.
rm -rf "$1/usr/share/doc"
