#!/bin/sh -e

patch -p0 < patch-src_libssl_compat_h.patch

./configure \
    --prefix=/usr \
    --disable-nls \
    --disable-metalink \
    --disable-websocket \
    --disable-epoll

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/man/ru"
rm -rf "$1/usr/share/man/pt"
