#!/bin/sh

cat <<EOF

NOTE: Install the 'firefox-privacy' package to
      enable extra privacy restrictions.

NOTE: This includes more telemetry removals,
      hardened settings, no phoning-home etc.

-> kiss b firefox-privacy
-> kiss i firefox-privacy

EOF
