#!/bin/sh -e

make
make DESTDIR="$1" ZICDIR=/usr/bin install

set -- africa asia australasia europe northamerica southamerica

./zic -d "$DESTDIR/usr/share/zoneinfo" "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo/posix" "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo/right" -L leapseconds "$@"
./zic -d "$DESTDIR/usr/share/zoneinfo" -p America/New_York
