#!/bin/sh -e

# plzip is the only thing that will ever require
# this library. Let's simply build it and statically
# compile plzip.
(cd lzlib; ./configure; make)

# Fix build in libc++ environment.
case $("${CC:-cc}" -print-file-name=libc++.a) in */*)
    CXXFLAGS="$CXXFLAGS -lunwind -lc++abi"
esac

./configure \
    --prefix=/usr \
    CXXFLAGS="$CXXFLAGS -static -L$PWD/lzlib -I$PWD/lzlib"

make
make install

# Create the symlink for compatibility. We're using
# a multi-threaded implementation of lzip.
ln -s plzip "$1/usr/bin/lzip"
