#!/bin/sh -e

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed 's/perl //;s/xml2lst\.pl/xml2lst/' rules/Makefile.in > _
mv -f _ rules/Makefile.in

./configure \
    --prefix=/usr \
    --enable-compat-rules \
    --without-xsltproc \
    --disable-runtime-deps \
    --disable-nls

make
make DESTDIR="$1" install
