#!/bin/sh -e

./configure \
    --prefix=/usr \
    --libexecdir=/usr/bin \
    --localstatedir=/var \
    --disable-dbus

make
make install

# Install runit service.
mkdir -p "$1/etc/sv/eiwd"
cp -f  eiwd.run                  "$1/etc/sv/eiwd/run"
ln -sf /run/runit/supervise.eiwd "$1/etc/sv/eiwd/supervise"
