#!/bin/sh -e

patch -p1 < mandoc-no-warn.patch

# Change default pager.
sed 's,"more -s","less",g' main.c > _
mv -f _ main.c

# Use CC rather than broken default.
sed "s/CC=.*/CC=${CC:-cc}/" configure > _
mv -f _ configure
chmod +x configure

cat > configure.local <<EOF
PREFIX=/usr
MANDIR=/usr/share/man
LIBDIR=/usr/lib
SBINDIR=/usr/bin
CC="${CC:-cc}"
CFLAGS="$CFLAGS -fcommon"
LN="ln -sf"
EOF

./configure

make
make -j1 DESTDIR="$1" base-install
