#!/bin/sh -e

./configure \
    --prefix=/usr

make
make DESTDIR="$1" install

mv "$1/lib/ld-musl-x86_64.so.1" "$1/usr/lib"
rmdir "$1/lib"

mkdir -p "$1/bin"
ln -s "/usr/lib/ld-musl-x86_64.so.1" "$1/usr/bin/ldd"
