#!/bin/sh -e

# Avoid scdoc dependency.
sed "/subdir('doc')/d" meson.build > _
mv -f _ meson.build

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=fcft,tllist \
    . output

ninja -C output
ninja -C output install
