#!/bin/sh -e

meson \
    --prefix=/usr \
    --buildtype=release \
    --force-fallback-for=fcft,tllist \
    -Dime=false \
    . output

ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/doc" \
    "$1/usr/share/zsh" \
    "$1/usr/share/fish" \
    "$1/usr/share/bash-completion"
