#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-pic

make
make DESTDIR="$1" install

# Maintain compatibility and avoid the need
# for rebuilds of all packages linking to
# libffi.
ln -s libffi.so.7 "$1/usr/lib/libffi.so.6"
