#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-threads \
    --with-history \
    --without-python \
    --without-icu

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/gtk-doc"
