#!/bin/sh -e

sed "s|pthread-stubs ||" -i configure.ac
autoreconf -fi

./configure \
    --prefix=/usr \
    --disable-build-docs

make
make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/doc"
