#!/bin/sh -e

cat <<EOF

NOTE: The gzip package will be removed 22/07/2021
      and replaced with pigz. Run the following
      to transition before the deadline.

      kiss b pigz
      kiss i pigz
      kiss a | grep ^pigz | kiss a -
      kiss r gzip

EOF
