#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

mkdir -p "$1/usr/bin"

make
make DESTDIR="$1" install

cd "$1/usr/bin"
ln -s pkgconf pkg-config

# Remove docs.
rm -rf "$1/usr/share/doc"
