#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-hwdb \
    --disable-introspection

make
make DESTDIR="$1" install

# Install runit service.
install -Dm755 udevd.run         "$1/etc/sv/udevd/run"
ln -s /run/runit/supervise.udevd "$1/etc/sv/udevd/supervise"
