#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sysconfdir=/etc

make
make DESTDIR="$1" install

# Remove all doc files.
rm -rf "$1/usr/share/doc"

# Remove all man/ru files.
rm -rf "$1/usr/share/man/ru"
