#!/bin/sh -e
#
# The Makefile uses install commands which are incompatible
# with busybox's install implementation (specifically -T).

mkdir -p "$1/usr/share/man"

for i in 0p 1p 3p; do
    cp -Rf "posix/man$i" "$1/usr/share/man/man${i%%p}"
done

for i in 2 4 5 7; do
    cp -Rf "man$i" "$1/usr/share/man"
done

# Provided by mandoc.
rm -f "$1/usr/share/man/man7/man.7"

# Provided by tzdata.
rm -f "$1/usr/share/man/man5/tzfile.5"
