#!/bin/sh -e
#
# The Makefile uses install commands which are incompatible
# with busybox's install implementation (specifically -T).

mkdir -p "$1/usr/share/man"

# The sources are set out as follows.
#
# 1. user commands (intro, plus a few other pages)
# 2. system calls
# 3. libc calls
# 4. devices (e.g., hd, sd)
# 5. file formats and configuration files (e.g., wtmp, /etc/passwd)
# 6. games (intro only)
# 7. overviews, conventions, macro packages, etc.
# 8. system administration (intro, plus a few other pages)
#
# Manual pages which relate to glibc or are otherwise provided by
# other packages (tzdata, etc) are excluded.
for i in 2 4 5 7; do
    cp -Rf "man$i" "$1/usr/share/man"
done

# Provided by mandoc.
rm -f "$1/usr/share/man/man7/man.7"

# Provided by tzdata.
rm -f "$1/usr/share/man/man5/tzfile.5"
