#!/bin/sh -e

# Use autotools to build mesa.
# Meson has no ability to disable 'gettext'.
./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --with-platforms=x11,drm \
    --enable-autotools

make
make DESTDIR="$1" install
