#!/bin/sh -e

patch -p1 < mesa-no-gettext.patch

export CFLAGS="-DGLX_X86_READONLY_TEXT $CFLAGS"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=release \
    -Dglx-use-tls=false \
    -Dplatforms=x11,drm \
    . output

ninja -C output

DESTDIR="$1" ninja -C output install
