#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-xinitdir=/etc/X11/xinit

make
make DESTDIR="$1" install

printf ",s/enable_xauth=1/enable_xauth=0/\nw\nq" |
    ed "$1/usr/bin/startx" >/dev/null
