#!/bin/sh

make CFLAGS="$CFLAGS -fPIC $LDFLAGS" LDFLAGS="$LDFLAGS" -f Makefile-libbz2_so
make CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" bzip2recover libbz2.a

install -Dm755 bzip2-shared "$1/usr/bin/bzip2"
ln -sf bzip2 "$1/usr/bin/bunzip2"
ln -sf bzip2 "$1/usr/bin/bzcat"
install -m755 bzdiff bzgrep bzmore bzip2recover "$1/usr/bin"

install -Dm755 libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0.8"
# Backwards compatibility with older programs
ln -s libbz2.so.1.0.8 "$1/usr/lib/libbz2.so"
ln -s libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1"
ln -s libbz2.so.1.0.8 "$1/usr/lib/libbz2.so.1.0"

install -m644 libbz2.a "$1/usr/lib"
install -Dm644 bzlib.h "$1/usr/include/bzlib.h"

install -Dm644 bzip2.1 "$1/usr/share/man/man1/bzip2.1"
ln -sf bzip2.1 "$1/usr/share/man/man1/bunzip2.1"
ln -sf bzip2.1 "$1/usr/share/man/man1/bzcat.1"
ln -sf bzip2.1 "$1/usr/share/man/man1/bzip2recover.1"
