#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-debug \
    --enable-gpl \
    --enable-version3 \
    --enable-libass \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libtheora \
    --enable-libwavpack \
    --enable-libvpx \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-libwebp \
    --enable-libdrm

make
make DESTDIR="$1" install

# Remove examples.
rm -rf "$1/usr/share/ffmpeg/examples"
