#!/bin/sh -e

python ./bootstrap.py
python waf configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --confdir=/etc/mpv \
    --enable-alsa \
    --enable-libass \
    --enable-libmpv-shared

python waf build
python waf install --destdir="$1"
