#!/bin/sh -e

make \
   PREFIX="/usr" \
   LIBS="-lncursesw" \
   DESTDIR="$1" \
   build \
   install

# Remove all doc files.
rm -rf "$1/usr/share/doc"

# Remove all info files.
rm -rf "$1/usr/share/info"
