#!/bin/sh -e

# Fix build fail with GCC 10.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --enable-noexecstack \
    --disable-nls

make
make install
