#!/bin/sh -e

BUILD_ZLIB=0
BUILD_BZIP2=0

./Configure \
    -des \
    -Dcccdlflags='-fPIC' \
    -Dcccdlflags='-fPIC' \
    -Dccdlflags='-rdynamic' \
    -Dprefix=/usr \
    -Dprivlib=/usr/share/perl5/core_perl \
    -Darchlib=/usr/lib/perl5/core_perl \
    -Dvendorprefix=/usr \
    -Dvendorlib=/usr/share/perl5/vendor_perl \
    -Dvendorarch=/usr/lib/perl5/vendor_perl \
    -Dsiteprefix=/usr/local \
    -Dsitelib=/usr/local/share/perl5/site_perl \
    -Dsitearch=/usr/local/lib/perl5/site_perl \
    -Dlocincpth=' ' \
    -Doptimize="$CFLAGS" \
    -Duselargefiles \
    -Dusethreads \
    -Duseshrplib \
    -Dd_semctl_semun \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dinstallman1dir=/usr/share/man/man1 \
    -Dinstallman3dir=/usr/share/man/man3 \
    -Dman1ext='1' \
    -Dman3ext='3pm' \
    -Dcf_by='KISS' \
    -Ud_csh \
    -Dusenm

make
make DESTDIR="$1" install

# Remove all .pod files except for those in:
# /usr/share/perl5/core_perl/pod/
for d in "$1/usr/share/perl5/core_perl/"*; do
    [ -d "$d" ] && [ "${d##*/}" != pod ] && {
        find "$d" -name "*.pod" -delete
    }
done

# Ditto.
rm -f "$1/usr/share/perl5/core_perl/"*.pod
find "$1/usr/lib" -name \*.pod -delete
find "$1" -name .packlist -delete
