#!/bin/sh -e

export BUILD_ZLIB=0
export BUILD_BZIP2=0
export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE"

./Configure \
    -des \
    -Dcccdlflags='-fPIC' \
    -Dcccdlflags='-fPIC' \
    -Dccdlflags='-rdynamic' \
    -Dprefix=/usr \
    -Dprivlib=/usr/share/perl5/core_perl \
    -Darchlib=/usr/lib/perl5/core_perl \
    -Dvendorprefix=/usr \
    -Dvendorlib=/usr/share/perl5/vendor_perl \
    -Dvendorarch=/usr/lib/perl5/vendor_perl \
    -Dsiteprefix=/usr/local \
    -Dsitelib=/usr/local/share/perl5/site_perl \
    -Dsitearch=/usr/local/lib/perl5/site_perl \
    -Dlocincpth=' ' \
    -Doptimize="$CFLAGS" \
    -Duselargefiles \
    -Dusethreads \
    -Duseshrplib \
    -Dd_semctl_semun \
    -Dman1dir=/usr/share/man/man1 \
    -Dman3dir=/usr/share/man/man3 \
    -Dinstallman1dir=/usr/share/man/man1 \
    -Dinstallman3dir=/usr/share/man/man3 \
    -Dman1ext='1' \
    -Dman3ext='3pm' \
    -Dcf_by='KISS' \
    -Ud_csh \
    -Dusenm

make
make DESTDIR="$1" install

# Remove all .pod/packlist files.
find "$1" -name "*.pod" -delete
find "$1" -name .packlist -delete

# Remove all documentation.
rm -rf "$1/usr/share/man"
