#!/bin/sh -e

patch -p1 < libinput-optional-udev.patch

export DESTDIR="$1"

# Meson build has no support for automatically using
# udev if available. This simply does the same.
kiss l eudev >/dev/null 2>&1 || udev=false

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    -Dudev="${udev:=true}" \
    -Dtools="$udev" \
    . output

ninja -C output
ninja -C output install
