#!/bin/sh

mkdir -p target/snapshot
cp cargo-bootstrap/cargo/bin/cargo cargo

./cargo update
./cargo build --release

install -Dm755 target/release/cargo "$1/usr/bin/cargo"
install -d "$1/usr/share/man/man1"
install -m644 src/etc/man/* "$1/usr/share/man/man1"
