#!/bin/sh -e

./configure \
    --prefix=/usr \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make install

ln -s flex "$1/usr/bin/lex"

# Remove READMEs and such.
rm -rf "$1/usr/share/doc"
