#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-shared \
    --disable-nls \
    ac_cv_func_malloc_0_nonnull=yes \
    ac_cv_func_realloc_0_nonnull=yes

make
make DESTDIR="$1" install

# Remove unneeded files.
rm -rf "$1/usr/share/info"
rm -rf "$1/usr/share/doc"
