#!/bin/sh -e

build_freetype() (
    cd freetype

    ./configure \
        --prefix=/usr \
        --enable-freetype-config \
        --with-harfbuzz="$2" \
        --with-bzip2=no \

    make
    make install
)

build_harfbuzz() (
    # Point Harfbuzz to the Freetype files.
    export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
    export LDFLAGS="$LDFLAGS -L$1/usr/lib"

    cd harfbuzz

    meson \
        --prefix=/usr \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    ninja -C output
    ninja -C output install
)

build_freetype "$1" no
build_harfbuzz "$1"

# Point Freetype to the Harfbuzz files.
export HARFBUZZ_CFLAGS="-I$PWD/harfbuzz/src"
export HARFBUZZ_LIBS="-L$PWD/harfbuzz/output/src -lharfbuzz"

build_freetype "$1" yes
