#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-static

make

make DESTDIR="$1" \
    install-pkgconfigDATA \
    install-exec

make DESTDIR="$1" -C lib \
    install-pkgincludeHEADERS \
    install-nodist_pkgincludeHEADERS
