#!/bin/sh -e

chown root:input "$KISS_ROOT/usr/bin/sway"
chmod g+s        "$KISS_ROOT/usr/bin/sway"

cat <<EOF

NOTE: You must be in the 'video', 'audio', and 'tty'
      groups. There is no 'input' group requirement
      as this sway binary is setgid input.

NOTE: You must set XDG_RUNTIME_DIR in your shellrc
      or .profile for things to work. This directory
      must exist and must be writable by your user.

      export XDG_RUNTIME_DIR=/run/user/\$(id -u)

NOTE: You must be the first to call DRMSetMaster.

      If you cannot fulfil this requirement, you must
      use the 'sway' package and run the 'seatd' daemon.

      Another option is to setuid root the sway binary.

      See: https://github.com/torvalds/linux/commit/45bc3d26c95a8fc63a7d8668ca9e57ef0883351c

NOTE: sway-tiny does not spawn a subshell for exec
      commands, it executes them directly. Use the full
      path to the program you would like to execute.

      # Will not work.
      bindsym \$mod+t exec foot

      # Works.
      bindsym \$mod+t exec /bin/foot

NOTE: This is a fork of sway for KISS Linux. Send all
      bugs/issues to kisslinux/repo and NOT upstream.

EOF
