#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --enable-static

make
make DESTDIR="$1" install

# This will be removed once 'xorgproto' 2019.2
# is released.
rm -f "$1/usr/include/X11/extensions/XKBgeom.h"
