#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --without-xmlto \
    --disable-specs \
    --enable-static

make
make DESTDIR="$1" install

# Conflicts with xorgproto.
rm -f "$1/usr/include/X11/extensions/XKBgeom.h"

# Remove library documentation.
rm -rf "$1/usr/share/man/man3"
