#!/bin/sh -e

CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --enable-static

make
make DESTDIR="$1" install

# Remove unneeded files.
rm -rf "$1/usr/share/doc"
rm -rf "$1/usr/share/man/man3"
