#!/bin/sh -e

./configure \
    AUTOMAKE=/bin/true \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --with-xmldir=/etc/fonts \
    --enable-static \
    --disable-nls

make
make DESTDIR="$1" install
