#!/bin/sh -e

# Remove 'atk-bridge' dependency which removes the 'dbus' dependency.
printf ',s/ATK_PACKAGES="atk atk-bridge-2.0"/ATK_PACKAGES="atk"\nw\nq' |
    ed configure >/dev/null

printf 'g/<atk-bridge.h>/d\ng/atk_bridge_adaptor_init/d\nw\nq' |
    ed gtk/a11y/gtkaccessibility.c >/dev/null

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-xkb \
    --enable-xinerama \
    --enable-xrandr \
    --enable-xfixes \
    --enable-xcomposite \
    --enable-xdamage \
    --enable-x11-backend \
    --enable-debug=no \
    --disable-schemas-compile \
    --disable-cups \
    --disable-papi \
    --disable-cloudprint \
    --enable-introspection=no \
    --enable-colord=no \
    --enable-gtk-doc-html=no

make
make DESTDIR="$1" install
