#!/bin/sh -e

patch -p0 < libtheora-1.1.1-libpng16.patch

./configure \
    --prefix=/usr

make
make -C lib     DESTDIR="$1" install
make -C include DESTDIR="$1" install
make            DESTDIR="$1" install-pkgconfigDATA
