#!/bin/sh -e

# Workaround for GCC 10 until upstream
# fixes the '-fno-common' issues.
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr \
    --disable-valgrind

make
make DESTDIR="$1" install
