#!/bin/sh -e

# Disable building 'cairo-sphinx'.
printf "%s\n" \
    "/BUILD_SPHINX_TRUE=/s/BUILD_SPHINX_TRUE=/BUILD_SPHINX_TRUE='#'" \
    "/BUILD_SPHINX_FALSE='#'/s/BUILD_SPHINX_FALSE='#'/BUILD_SPHINX_FALSE=" \
    "w" "q" |
    ed configure >/dev/null

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-tee \
    --enable-gl \
    --enable-egl \
    --enable-xlib-xcb \
    --enable-xcb \
    --enable-xlib-xrender \
    --enable-xlib \
    --disable-trace \
    --disable-valgrind \
    --disable-gtk-doc-html

make
make DESTDIR="$1" install
