#!/bin/sh -e

./configure \
    --prefix=/usr \
    --enable-cscope \
    --enable-multibyte \
    --with-tlib=ncursesw \
    --with-ex-name=vim-ex \
    --with-view-name=vim-view \
    --disable-perlinterp \
    --disable-pythoninterp \
    --disable-rubyinterp \
    --disable-netbeans \
    --disable-gpm \
    --disable-hangulinput \
    --disable-xim \
    --disable-gui \
    --without-x

make
make DESTDIR="$1" install
