#!/bin/sh -e

install -Dm 755 rc.boot "$1/lib/init/rc.boot"
install -Dm 755 rc.shutdown "$1/lib/init/rc.shutdown"

install -Dm 755 rc.conf "$1/etc/rc.conf"
mkdir -p /etc/rc.d

install -Dm 755 inittab "$1/etc/inittab"
