#!/bin/sh -e

sed 's|Liberation Mono|Monospace|g' config.def.h > _
mv -f _ config.def.h

# Install terminfo to right location.
export TERMINFO="$1/usr/share/terminfo"
mkdir -p "$TERMINFO"

make
make PREFIX=/usr DESTDIR="$1" install
