#!/bin/sh -e

export DESTDIR="$1"

# First substitution disables weird case where build may try to git clone
# some repository related to documentation.
sed -e "s/'gi-docgen', '/'/" \
    -e "/subdir('tests')/d" \
    -e "/subdir('examples')/d" \
    meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    -Dgir=false \
    -Dgtk_doc=false \
    -Dintrospection=disabled \
    -Dinstalled_tests=false \
    . build

ninja -C build
ninja -C build install
