#!/bin/sh -e

# Grab the package version.
read -r version _ < "${0%/*}/version"

mkdir -p "$1/boot" "$1/usr/lib/modules"

make

make \
    INSTALL_PATH="$1/boot" \
    INSTALL_MOD_PATH="$1/usr" \
    modules_install

make \
    INSTALL_PATH="$1/boot" \
    INSTALL_MOD_PATH="$1/usr" \
    install

# Rename 'vmlinuz' and 'System.map" according to package version.
mv "$1/boot/vmlinuz" "$1/boot/vmlinuz-$version" || :
mv "$1/boot/System.map" "$1/boot/System.map-$version" || :
