#!/bin/sh -e

# Disable building 'cairo-sphinx'.
sed -e "s/\(BUILD_SPHINX_TRUE=\)/\1'#'/" \
    -e "s/\(BUILD_SPHINX_FALSE=\)'#'/\1=/" \
    configure > _
mv -f _ configure

# Disable building tests and documentation.
sed 's/boilerplate test perf//g;s/src doc/src/g' Makefile.in > _
mv -f _ Makefile.in

sh ./configure \
    --prefix=/usr \
    --disable-static \
    --enable-tee \
    --disable-xlib-xcb \
    --disable-xcb \
    --disable-xlib-xrender \
    --disable-xlib \
    --disable-trace \
    --disable-valgrind \
    --disable-gtk-doc-html

make
make install
