#!/bin/sh -e

# Disable building 'cairo-sphinx'.
sed -e "s/\(BUILD_SPHINX_TRUE=\)/\1'#'/" \
    -e "s/\(BUILD_SPHINX_FALSE=\)'#'/\1=/" \
    configure > _
mv -f _ configure
chmod +x configure

# Disable building tests and documentation.
sed 's/test perf//g;s/src doc/src/g' Makefile.in > _
mv -f _ Makefile.in

./configure \
    --prefix=/usr \
    --disable-static \
    --enable-tee \
    --enable-gl \
    --enable-egl \
    --enable-xlib-xcb \
    --enable-xcb \
    --enable-xlib-xrender \
    --enable-xlib \
    --disable-trace \
    --disable-valgrind \
    --disable-gtk-doc-html

make
make DESTDIR="$1" install
