#!/bin/sh -e

# Fix build with Python 3.10.
cat << EOF | ed deps/v8/third_party/jinja2/tests.py >/dev/null
/collections/s/collections/collections.abc
w
q
EOF

cat << EOF | ed configure >/dev/null
/acceptable_pythons = /s/(3, 9)/(3, 10), (3, 9)
6a
command -v python3.10 >/dev/null && exec python3.10 "\$0" "\$@"
.
w
q
EOF

# Fix build when libatomic.so does not exist in the system.
# This may be provided by compiler-rt which requires no additional
# linker flags to be used.
[ -r "$KISS_ROOT/usr/lib/libatomic.so" ] || {
    sed 's/-latomic//' node.gyp > _
    mv -f _ node.gyp
}

./configure \
    --shared-zlib \
    --shared-openssl \
    --with-intl=none \
    --without-etw \
    --without-dtrace \
    --without-report \
    --without-node-snapshot \
    --without-node-code-cache \
    --ninja

ninja -C out/Release
tools/install.py install "$1" /usr

# Remove unneeded files.
rm -rf \
    "$1/usr/include/node/openssl" \
    "$1/usr/share/doc" \
    "$1/usr/share/systemtap" \
    "$1/usr/lib/node_modules/npm/scripts" \
    "$1/usr/lib/node_modules/npm/configure"
