#!/bin/sh -e

CFLAGS="$CFLAGS -DDEFAULT_TT_INTERPRETER_VERSION=TT_INTERPRETER_VERSION_40" \
./configure \
    --prefix=/usr \
    --enable-freetype-config \
    --with-harfbuzz=no

make
make DESTDIR="$1" install
