#!/bin/sh -e

patch -p1 < silence-dlerror.patch
patch -p0 < fakeroot-no64.patch
patch -p0 < fakeroot-stdint.patch
patch -p0 < busybox_compat_force_abslibpath.patch
patch -p1 < xstatjunk.patch

export CONFIG_SHELL=/bin/sh
export CFLAGS="-D_STAT_VER=0 $CFLAGS"

./bootstrap

ac_cv_func_capset=no \
./configure \
    --prefix=/usr \
    --disable-static

make DESTDIR="$1" install

# Remove docs.
rm -rf "$1/usr/share/man/nl"
rm -rf "$1/usr/share/man/pt"
rm -rf "$1/usr/share/man/sv"
rm -rf "$1/usr/share/man/fr"
rm -rf "$1/usr/share/man/es"
rm -rf "$1/usr/share/man/de"
