#!/bin/sh -e

export CC="${CC:-cc}"
export CXX="${CC:-c++}"

patch -p1 < x264-no-bash.patch

./configure \
    --prefix=/usr \
    --disable-swscale \
    --enable-static \
    --enable-pic \
    --enable-shared

make
make DESTDIR="$1" install
