#!/bin/sh -e

# Build fails in with clang due to
# -Werror -> -Wsign-compare.
export CFLAGS="-Wno-error $CFLAGS"

meson \
    --prefix=/usr \
    -Ddefault_library=both \
    . build

ninja -C build
ninja -C build install

# Install runit service.
mkdir -p "$1/etc/sv/seatd"
cp -f seatd.run "$1/etc/sv/seatd/run"
ln -sf /run/runit/supervise.seatd "$1/etc/sv/seatd/supervise"
